{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "dbad7ad9",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-12-04 12:24:22.347 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager\n",
      "2025-12-04 12:24:22.347 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:22.636 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run c:\\Users\\User\\Desktop\\ML Parami Midterm Project\\venv\\Lib\\site-packages\\ipykernel_launcher.py [ARGUMENTS]\n",
      "2025-12-04 12:24:22.638 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:22.639 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:22.640 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:23.156 Thread 'Thread-3': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:23.156 Thread 'Thread-3': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:23.156 Thread 'Thread-3': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.274 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.274 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.274 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.274 No runtime found, using MemoryCacheStorageManager\n",
      "2025-12-04 12:24:25.274 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.274 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.274 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.285 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.527 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.527 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.527 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.586 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.588 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.589 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.590 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.591 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.591 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.593 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.594 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.594 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.594 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.594 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.599 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.599 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.602 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.603 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.605 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.607 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.609 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.609 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.611 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.612 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.614 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.616 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.618 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.620 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.622 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.623 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.626 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.626 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.629 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.629 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.629 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.629 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.635 Session state does not function when running a script without `streamlit run`\n",
      "2025-12-04 12:24:25.637 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.639 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.641 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.642 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.642 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.646 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.646 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.648 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.648 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.650 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.653 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.656 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.658 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.659 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.662 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.664 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.665 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.667 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.669 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.671 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.672 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.673 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.674 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.675 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.677 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.679 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.681 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.681 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.687 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.689 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.691 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.691 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.691 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.691 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.696 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.696 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.696 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.699 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.701 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.703 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.704 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.704 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.704 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.704 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.710 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.710 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.712 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.712 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.714 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.714 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.714 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.720 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.721 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.721 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.724 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.724 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.727 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.729 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.729 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.729 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.729 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.734 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.736 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.736 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.736 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.736 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.736 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.736 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.745 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.746 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.748 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.750 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.753 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.756 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.757 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.758 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.759 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.759 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.762 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.762 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.762 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.762 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.770 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.772 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.773 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.776 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.776 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.778 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.778 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.780 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.781 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.781 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.781 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.785 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.790 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.792 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.793 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.794 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.796 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.797 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.798 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.798 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.799 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.800 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.803 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.806 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.807 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.809 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.811 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.813 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.814 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.815 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.817 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.818 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.821 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.822 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.822 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.822 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.826 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.829 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.831 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.832 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.833 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.836 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.837 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.839 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.841 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.843 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.845 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.846 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.849 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.850 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.851 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.853 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.854 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.856 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.856 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.856 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.856 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.856 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.862 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.863 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.865 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.866 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.867 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.869 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.873 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-04 12:24:25.873 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    }
   ],
   "source": [
    "import streamlit as st\n",
    "import pickle\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "from datetime import datetime\n",
    "\n",
    "# Load model\n",
    "@st.cache_resource\n",
    "def load_model():\n",
    "    with open('flight_delay.pkl', 'rb') as f:\n",
    "        return pickle.load(f)\n",
    "\n",
    "# Load mapping data\n",
    "@st.cache_data\n",
    "def load_mapping_data():\n",
    "    # Load flight data for unique values\n",
    "    flight = pd.read_csv('flights.csv', nrows=50000)\n",
    "    flight = flight[(flight['ARRIVAL_DELAY'].notna()) & \n",
    "                   (flight['CANCELLED'] == 0) & \n",
    "                   (flight['DIVERTED'] == 0)]\n",
    "    \n",
    "    # Load airport and airline mappings\n",
    "    airports_df = pd.read_csv('airports.csv')\n",
    "    airlines_df = pd.read_csv('airlines.csv')\n",
    "    \n",
    "    # Create mapping dictionaries\n",
    "    airport_name_mapping = dict(zip(airports_df['IATA_CODE'], airports_df['AIRPORT']))\n",
    "    airline_name_mapping = dict(zip(airlines_df['IATA_CODE'], airlines_df['AIRLINE']))\n",
    "    \n",
    "    # Get unique values from flight data\n",
    "    unique_airlines = sorted(flight['AIRLINE'].unique())\n",
    "    unique_origin_airports = sorted(flight['ORIGIN_AIRPORT'].unique())\n",
    "    unique_destination_airports = sorted(flight['DESTINATION_AIRPORT'].unique())\n",
    "    \n",
    "    # Create dropdown options with names\n",
    "    airline_options = {}\n",
    "    for code in unique_airlines:\n",
    "        name = airline_name_mapping.get(code, f\"Unknown ({code})\")\n",
    "        airline_options[code] = name\n",
    "    \n",
    "    airport_options = {}\n",
    "    for code in unique_origin_airports:\n",
    "        name = airport_name_mapping.get(code, f\"Unknown ({code})\")\n",
    "        airport_options[code] = name\n",
    "    \n",
    "    return {\n",
    "        'flight': flight,\n",
    "        'airline_options': airline_options,\n",
    "        'airport_options': airport_options,\n",
    "        'unique_airlines': unique_airlines,\n",
    "        'unique_origin_airports': unique_origin_airports,\n",
    "        'unique_destination_airports': unique_destination_airports,\n",
    "        'airline_name_mapping': airline_name_mapping,\n",
    "        'airport_name_mapping': airport_name_mapping\n",
    "    }\n",
    "\n",
    "# Calculate derived features\n",
    "def calculate_derived_features(input_dict):\n",
    "    \"\"\"Calculate all derived features from basic inputs\"\"\"\n",
    "    hour_of_day = input_dict['scheduled_departure']\n",
    "    \n",
    "    derived = {\n",
    "        'hour_of_day': hour_of_day,\n",
    "        'is_morning_rush': 1 if hour_of_day in [6, 7, 8] else 0,\n",
    "        'is_evening_rush': 1 if hour_of_day in [17, 18, 19] else 0,\n",
    "        'is_night_flight': 1 if hour_of_day in [22, 23, 0, 1, 2, 3, 4, 5] else 0,\n",
    "        'is_weekend': 1 if input_dict['day_of_week'] in [6, 7] else 0,\n",
    "        'winter_month': 1 if input_dict['month'] in [12, 1, 2] else 0,\n",
    "        'summer_month': 1 if input_dict['month'] in [6, 7, 8] else 0,\n",
    "        'holiday_season': 1 if input_dict['month'] in [11, 12] else 0,\n",
    "        'is_short_flight': 1 if input_dict['distance'] < 500 else 0,\n",
    "        'is_long_flight': 1 if input_dict['distance'] > 2000 else 0\n",
    "    }\n",
    "    \n",
    "    return derived\n",
    "\n",
    "# Load model and data\n",
    "model = load_model()\n",
    "data = load_mapping_data()\n",
    "\n",
    "# Streamlit app\n",
    "st.set_page_config(\n",
    "    page_title=\"Flight Delay Predictor\",\n",
    "    page_icon=\"✈️\",\n",
    "    layout=\"wide\"\n",
    ")\n",
    "\n",
    "# Title and description\n",
    "st.title(\"✈️ Flight Delay Predictor\")\n",
    "st.markdown(\"\"\"\n",
    "Predict whether your flight will be delayed by more than 15 minutes based on various factors.\n",
    "\"\"\")\n",
    "\n",
    "# Create a sidebar for additional info\n",
    "with st.sidebar:\n",
    "    st.header(\"ℹ️ About\")\n",
    "    st.markdown(\"\"\"\n",
    "    This model predicts flight delays using:\n",
    "    - Airline and airport information\n",
    "    - Date and time of flight\n",
    "    - Flight duration and distance\n",
    "    - Derived features (rush hour, season, etc.)\n",
    "    \n",
    "    **Threshold**: Delay > 15 minutes\n",
    "    \"\"\")\n",
    "    \n",
    "    st.header(\"📊 Model Info\")\n",
    "    st.markdown(\"\"\"\n",
    "    - **Algorithm**: Random Forest Classifier\n",
    "    - **Training data**: 50,000 flight records\n",
    "    - **Features**: 18 total features\n",
    "    - **Preprocessing**: SMOTE for class balancing\n",
    "    \"\"\")\n",
    "\n",
    "# Main content area\n",
    "st.header(\"Flight Details\")\n",
    "\n",
    "# Create columns for better layout\n",
    "col1, col2, col3 = st.columns(3)\n",
    "\n",
    "with col1:\n",
    "    st.subheader(\"🛫 Origin\")\n",
    "    origin_code = st.selectbox(\n",
    "        \"Select Origin Airport\",\n",
    "        options=data['unique_origin_airports'],\n",
    "        format_func=lambda x: f\"{x} - {data['airport_options'].get(x, x)}\",\n",
    "        key=\"origin_select\"\n",
    "    )\n",
    "    \n",
    "    # Show airport info\n",
    "    if origin_code in data['airport_name_mapping']:\n",
    "        st.caption(f\"**Airport**: {data['airport_name_mapping'][origin_code]}\")\n",
    "\n",
    "with col2:\n",
    "    st.subheader(\"🛬 Destination\")\n",
    "    dest_code = st.selectbox(\n",
    "        \"Select Destination Airport\",\n",
    "        options=data['unique_destination_airports'],\n",
    "        format_func=lambda x: f\"{x} - {data['airport_options'].get(x, x)}\",\n",
    "        key=\"dest_select\"\n",
    "    )\n",
    "    \n",
    "    # Show airport info\n",
    "    if dest_code in data['airport_name_mapping']:\n",
    "        st.caption(f\"**Airport**: {data['airport_name_mapping'][dest_code]}\")\n",
    "\n",
    "with col3:\n",
    "    st.subheader(\"✈️ Airline\")\n",
    "    airline_code = st.selectbox(\n",
    "        \"Select Airline\",\n",
    "        options=data['unique_airlines'],\n",
    "        format_func=lambda x: f\"{x} - {data['airline_options'].get(x, x)}\",\n",
    "        key=\"airline_select\"\n",
    "    )\n",
    "    \n",
    "    # Show airline info\n",
    "    if airline_code in data['airline_name_mapping']:\n",
    "        st.caption(f\"**Airline**: {data['airline_name_mapping'][airline_code]}\")\n",
    "\n",
    "# Divider\n",
    "st.divider()\n",
    "\n",
    "# Flight details in columns\n",
    "st.header(\"📅 Flight Schedule\")\n",
    "\n",
    "col4, col5, col6 = st.columns(3)\n",
    "\n",
    "with col4:\n",
    "    st.subheader(\"Date\")\n",
    "    month = st.selectbox(\n",
    "        \"Month\", \n",
    "        options=list(range(1, 13)),\n",
    "        format_func=lambda x: datetime(2024, x, 1).strftime('%B')\n",
    "    )\n",
    "    day = st.selectbox(\"Day\", options=list(range(1, 32)))\n",
    "\n",
    "with col5:\n",
    "    st.subheader(\"Time\")\n",
    "    day_of_week = st.selectbox(\n",
    "        \"Day of Week\", \n",
    "        options=list(range(1, 8)),\n",
    "        format_func=lambda x: [\"Monday\", \"Tuesday\", \"Wednesday\", \n",
    "                              \"Thursday\", \"Friday\", \"Saturday\", \"Sunday\"][x-1]\n",
    "    )\n",
    "    \n",
    "    # Scheduled departure in 24-hour format\n",
    "    scheduled_departure = st.slider(\n",
    "        \"Departure Hour (24-hour format)\",\n",
    "        min_value=0,\n",
    "        max_value=23,\n",
    "        value=12,\n",
    "        help=\"Hour of departure in 24-hour format (0-23)\"\n",
    "    )\n",
    "    \n",
    "    # Format display\n",
    "    am_pm = \"AM\" if scheduled_departure < 12 else \"PM\"\n",
    "    hour_display = scheduled_departure if scheduled_departure <= 12 else scheduled_departure - 12\n",
    "    if hour_display == 0:\n",
    "        hour_display = 12\n",
    "    st.caption(f\"**Departure Time**: {hour_display}:00 {am_pm}\")\n",
    "\n",
    "with col6:\n",
    "    st.subheader(\"Flight Info\")\n",
    "    distance = st.slider(\n",
    "        \"Flight Distance (miles)\",\n",
    "        min_value=50,\n",
    "        max_value=3000,\n",
    "        value=500,\n",
    "        step=50,\n",
    "        help=\"Distance between origin and destination airports\"\n",
    "    )\n",
    "    \n",
    "    scheduled_time = st.slider(\n",
    "        \"Scheduled Flight Time (minutes)\",\n",
    "        min_value=30,\n",
    "        max_value=600,\n",
    "        value=120,\n",
    "        step=15,\n",
    "        help=\"Expected flight duration from takeoff to landing\"\n",
    "    )\n",
    "    \n",
    "    # Calculate arrival time\n",
    "    arrival_hour = (scheduled_departure + (scheduled_time // 60)) % 24\n",
    "    am_pm_arrival = \"AM\" if arrival_hour < 12 else \"PM\"\n",
    "    hour_display_arrival = arrival_hour if arrival_hour <= 12 else arrival_hour - 12\n",
    "    if hour_display_arrival == 0:\n",
    "        hour_display_arrival = 12\n",
    "    st.caption(f\"**Estimated Arrival**: {hour_display_arrival}:00 {am_pm_arrival}\")\n",
    "\n",
    "# Divider\n",
    "st.divider()\n",
    "\n",
    "# Show derived features\n",
    "st.header(\"📈 Derived Features\")\n",
    "\n",
    "# Calculate derived features\n",
    "input_data = {\n",
    "    'scheduled_departure': scheduled_departure,\n",
    "    'day_of_week': day_of_week,\n",
    "    'month': month,\n",
    "    'distance': distance\n",
    "}\n",
    "\n",
    "derived_features = calculate_derived_features(input_data)\n",
    "\n",
    "# Display derived features in a nice way\n",
    "col7, col8, col9 = st.columns(3)\n",
    "\n",
    "with col7:\n",
    "    st.metric(\"Rush Hour\", \n",
    "              \"Morning\" if derived_features['is_morning_rush'] == 1 else \n",
    "              \"Evening\" if derived_features['is_evening_rush'] == 1 else \"Normal\")\n",
    "    st.metric(\"Weekend\", \"Yes\" if derived_features['is_weekend'] == 1 else \"No\")\n",
    "\n",
    "with col8:\n",
    "    season = \"Winter\" if derived_features['winter_month'] == 1 else \\\n",
    "             \"Summer\" if derived_features['summer_month'] == 1 else \\\n",
    "             \"Holiday\" if derived_features['holiday_season'] == 1 else \"Regular\"\n",
    "    st.metric(\"Season\", season)\n",
    "    st.metric(\"Night Flight\", \"Yes\" if derived_features['is_night_flight'] == 1 else \"No\")\n",
    "\n",
    "with col9:\n",
    "    flight_length = \"Short\" if derived_features['is_short_flight'] == 1 else \\\n",
    "                   \"Long\" if derived_features['is_long_flight'] == 1 else \"Medium\"\n",
    "    st.metric(\"Flight Length\", flight_length)\n",
    "    st.metric(\"Distance Category\", f\"{distance} miles\")\n",
    "\n",
    "# Prediction button\n",
    "st.divider()\n",
    "st.header(\"🎯 Prediction\")\n",
    "\n",
    "if st.button(\"Predict Delay Probability\", type=\"primary\", use_container_width=True):\n",
    "    try:\n",
    "        # Create input DataFrame with all features\n",
    "        user_data = pd.DataFrame([{\n",
    "            'ORIGIN_AIRPORT': origin_code,\n",
    "            'AIRLINE': airline_code,\n",
    "            'DESTINATION_AIRPORT': dest_code,\n",
    "            'MONTH': month,\n",
    "            'DAY': day,\n",
    "            'DAY_OF_WEEK': day_of_week,\n",
    "            'SCHEDULED_DEPARTURE': scheduled_departure * 100,  # Convert to HHMM format\n",
    "            'SCHEDULED_ARRIVAL': (scheduled_departure * 100 + scheduled_time) % 2400,\n",
    "            'SCHEDULED_TIME': scheduled_time,\n",
    "            'DISTANCE': distance,\n",
    "            'hour_of_day': scheduled_departure,\n",
    "            'is_morning_rush': derived_features['is_morning_rush'],\n",
    "            'is_evening_rush': derived_features['is_evening_rush'],\n",
    "            'is_night_flight': derived_features['is_night_flight'],\n",
    "            'is_weekend': derived_features['is_weekend'],\n",
    "            'winter_month': derived_features['winter_month'],\n",
    "            'summer_month': derived_features['summer_month'],\n",
    "            'holiday_season': derived_features['holiday_season'],\n",
    "            'is_short_flight': derived_features['is_short_flight'],\n",
    "            'is_long_flight': derived_features['is_long_flight']\n",
    "        }])\n",
    "        \n",
    "        # Make prediction\n",
    "        prediction = model.predict(user_data)\n",
    "        probabilities = model.predict_proba(user_data)\n",
    "        \n",
    "        # Display results\n",
    "        st.subheader(\"Prediction Results\")\n",
    "        \n",
    "        # Create columns for results\n",
    "        result_col1, result_col2 = st.columns(2)\n",
    "        \n",
    "        with result_col1:\n",
    "            delay_prob = probabilities[0][1] * 100\n",
    "            on_time_prob = probabilities[0][0] * 100\n",
    "            \n",
    "            st.metric(\"Delay Probability\", f\"{delay_prob:.1f}%\")\n",
    "            st.metric(\"On-Time Probability\", f\"{on_time_prob:.1f}%\")\n",
    "        \n",
    "        with result_col2:\n",
    "            if prediction[0] == 1:\n",
    "                st.error(\"⚠️ **FLIGHT LIKELY TO BE DELAYED**\")\n",
    "                st.markdown(\"**Prediction**: Delay > 15 minutes\")\n",
    "            else:\n",
    "                st.success(\"✅ **FLIGHT LIKELY TO BE ON TIME**\")\n",
    "                st.markdown(\"**Prediction**: Delay ≤ 15 minutes\")\n",
    "        \n",
    "        # Show detailed breakdown\n",
    "        with st.expander(\"View Detailed Analysis\"):\n",
    "            st.markdown(\"### Feature Analysis\")\n",
    "            \n",
    "            # Display input features\n",
    "            st.markdown(\"#### Input Features:\")\n",
    "            feature_col1, feature_col2 = st.columns(2)\n",
    "            \n",
    "            with feature_col1:\n",
    "                st.write(f\"**Airline**: {data['airline_name_mapping'].get(airline_code, airline_code)}\")\n",
    "                st.write(f\"**Origin**: {data['airport_name_mapping'].get(origin_code, origin_code)}\")\n",
    "                st.write(f\"**Destination**: {data['airport_name_mapping'].get(dest_code, dest_code)}\")\n",
    "                st.write(f\"**Date**: Month {month}, Day {day}\")\n",
    "                \n",
    "            with feature_col2:\n",
    "                st.write(f\"**Departure**: {scheduled_departure}:00\")\n",
    "                st.write(f\"**Flight Time**: {scheduled_time} minutes\")\n",
    "                st.write(f\"**Distance**: {distance} miles\")\n",
    "                st.write(f\"**Day of Week**: {['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'][day_of_week-1]}\")\n",
    "            \n",
    "            # Display derived features\n",
    "            st.markdown(\"#### Derived Features:\")\n",
    "            derived_col1, derived_col2 = st.columns(2)\n",
    "            \n",
    "            with derived_col1:\n",
    "                st.write(f\"**Rush Hour**: {'Yes' if derived_features['is_morning_rush'] == 1 or derived_features['is_evening_rush'] == 1 else 'No'}\")\n",
    "                st.write(f\"**Weekend**: {'Yes' if derived_features['is_weekend'] == 1 else 'No'}\")\n",
    "                st.write(f\"**Night Flight**: {'Yes' if derived_features['is_night_flight'] == 1 else 'No'}\")\n",
    "                \n",
    "            with derived_col2:\n",
    "                st.write(f\"**Season**: {season}\")\n",
    "                st.write(f\"**Flight Length**: {flight_length}\")\n",
    "                st.write(f\"**Holiday Season**: {'Yes' if derived_features['holiday_season'] == 1 else 'No'}\")\n",
    "        \n",
    "        # Show recommendations\n",
    "        st.subheader(\"📋 Recommendations\")\n",
    "        if prediction[0] == 1:\n",
    "            st.warning(\"\"\"\n",
    "            **Consider these options:**\n",
    "            - Book an earlier flight if possible\n",
    "            - Choose a different airline\n",
    "            - Avoid rush hour flights\n",
    "            - Allow extra time for connections\n",
    "            - Consider travel insurance\n",
    "            \"\"\")\n",
    "        else:\n",
    "            st.info(\"\"\"\n",
    "            **Good news! Your flight has a high on-time probability.**\n",
    "            - Proceed with your travel plans\n",
    "            - Still allow some buffer time for unexpected delays\n",
    "            - Check in online to save time at the airport\n",
    "            \"\"\")\n",
    "            \n",
    "    except Exception as e:\n",
    "        st.error(f\"An error occurred during prediction: {str(e)}\")\n",
    "        st.info(\"Please check that all inputs are valid and try again.\")\n",
    "\n",
    "# Footer\n",
    "st.divider()\n",
    "st.caption(\"\"\"\n",
    "**Note**: This prediction is based on historical data and machine learning models. \n",
    "Actual flight delays may vary due to unforeseen circumstances such as weather, \n",
    "air traffic control issues, or operational changes by the airline.\n",
    "\"\"\")\n",
    "\n",
    "# Add a reset button\n",
    "if st.button(\"Reset Form\", type=\"secondary\"):\n",
    "    st.rerun()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "venv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
